repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: [ --no-error-on-unmatched-pattern ]
        additional_dependencies:
          - eslint@8.56.0
          - typescript@5.3.3
          - "@typescript-eslint/parser@7.0.0"
          - "@typescript-eslint/eslint-plugin@7.0.0"
          - eslint-config-next@14.2.3
          - eslint-plugin-react@7.34.1
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-jsx-a11y@6.8.0
