"""
LangGraph Agent Workflow for AG Associates AI
Implements the 3-node pipeline: Aisha -> Drafter -> Auditor
"""

import os
from typing import TypedDict, List, Dict, Any, Optional
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
import psycopg2
from psycopg2.extras import RealDictCursor
from pgvector.psycopg2 import register_vector
import json
import re
from datetime import datetime
from tenacity import retry, stop_after_attempt, wait_exponential
from config import get_database_url, EMBEDDING_MODEL_NAME, LLM_MODEL_NAME, LLM_BASE_URL
from langsmith import traceable

try:
    from workforce.ledger import record_activity as _record_activity
except Exception:  # workforce schema may not be migrated in some envs
    def _record_activity(**_kwargs):  # type: ignore
        return None


class AgentState(TypedDict):
    """
    State schema for the agent workflow
    Tracks all variables through the pipeline
    """
    # Input from user
    raw_input: str
    sender: str
    org_id: Optional[str]

    # Extracted by Aisha
    tenant_name: Optional[str]
    landlord_name: Optional[str]
    rent_amount: Optional[str]
    property_address: Optional[str]
    agreement_start_date: Optional[str]
    agreement_duration: Optional[str]
    security_deposit: Optional[str]
    stamp_duty_paid: Optional[str]
    extracted_json: Optional[Dict[str, Any]]
    
    # Generated by Drafter
    template_id: Optional[int]
    template_content: Optional[str]
    drafted_document: Optional[str]
    pdf_path: Optional[str]
    
    # Guardrail result
    guardrail_passed: bool
    bouncer_passed: bool
    bouncer_feedback: Optional[str]

    # Audit results
    audit_passed: bool
    audit_feedback: Optional[str]
    revision_count: int
    
    # Metadata
    current_node: str
    errors: List[str]
    timestamps: Dict[str, str]


def get_db_connection():
    """Create database connection with pgvector support"""
    conn = psycopg2.connect(
        get_database_url(),
        cursor_factory=RealDictCursor
    )
    register_vector(conn)
    return conn


# Lazy-loaded SentenceTransformer — initialised on first call to avoid
# import-time overhead and to keep startup fast when the backend is used
# without any RAG queries (e.g. health checks).
_embedding_model = None


def _get_embedding_model():
    global _embedding_model
    if _embedding_model is None:
        from sentence_transformers import SentenceTransformer
        _embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
    return _embedding_model


def generate_embedding(text: str) -> List[float]:
    """
    Generate a real vector embedding for the given text using SentenceTransformer.
    """
    model = _get_embedding_model()
    embedding = model.encode(text)
    return embedding.tolist()


def similarity_search(query: str, limit: int = 3) -> List[Dict[str, Any]]:
    """
    Perform similarity search in PostgreSQL to find relevant templates
    """
    # Generate embedding for the query
    query_embedding = generate_embedding(query)

    conn = get_db_connection()
    try:
        cur = conn.cursor()
        try:
            # Perform vector similarity search
            cur.execute("""
                SELECT id, title, content, language, jurisdiction,
                       1 - (embedding <=> %s::vector) as similarity
                FROM legal_templates
                ORDER BY embedding <=> %s::vector
                LIMIT %s
            """, (query_embedding, query_embedding, limit))

            results = cur.fetchall()
        finally:
            cur.close()
    finally:
        conn.close()

    return [dict(row) for row in results]


# ============================================================================
# LLM RETRY UTILITY
# ============================================================================

@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10), reraise=True)
def invoke_llm_with_retry(chain, inputs):
    return chain.invoke(inputs)


# ============================================================================
# NODE 1: AISHA (Intake Agent)
# ============================================================================

AISHA_SYSTEM_PROMPT = """You are Aisha, the Intake Agent for AG Associates Legal AI.
Your role is to extract structured information from raw user messages about rental agreements.

EXTRACT THE FOLLOWING VARIABLES:
- tenant_name: Full name of the tenant
- landlord_name: Full name of the landlord/property owner
- rent_amount: Monthly rent amount (with currency)
- property_address: Complete address of the rental property
- agreement_start_date: Start date of the agreement
- agreement_duration: Duration of the agreement (e.g., "11 months", "1 year")
- security_deposit: Security deposit amount (with currency)
- stamp_duty_paid: Amount of stamp duty paid (with currency)

IMPORTANT RULES:
1. Output ONLY valid JSON - no explanations, no markdown
2. If a field cannot be extracted, set it to null
3. Standardize dates to YYYY-MM-DD format when possible
4. Include all monetary amounts with currency symbols
5. Be careful with Indic names and addresses - preserve exact spelling

EXAMPLE OUTPUT:
{
    "tenant_name": "Rajesh Kumar Sharma",
    "landlord_name": "Priya Deshmukh",
    "rent_amount": "₹25,000 per month",
    "property_address": "Flat No. 302, Shivaji Nagar, Pune, Maharashtra 411005",
    "agreement_start_date": "2024-02-01",
    "agreement_duration": "11 months",
    "security_deposit": "₹75,000",
    "stamp_duty_paid": "₹330"
}
"""


@traceable(name="Aisha_Intake_Agent")
def aisha_intake_node(state: AgentState) -> AgentState:
    """
    Node 1: Aisha - Extract variables from user's raw text
    """
    print(f"\n🧠 [AISHA] Processing intake for sender: {state['sender']}")
    state['current_node'] = 'aisha_intake'
    state['timestamps']['aisha_start'] = datetime.now().isoformat()
    
    try:
        # Initialize LLM (configured to use local vLLM server)
        llm = ChatOpenAI(
            model=LLM_MODEL_NAME,
            openai_api_base=LLM_BASE_URL,
            openai_api_key=os.environ.get("LLM_API_KEY", "not-needed"),
            temperature=0.1
        )
        
        # Create prompt template
        prompt = ChatPromptTemplate.from_messages([
            ("system", AISHA_SYSTEM_PROMPT),
            ("human", "Extract variables from this message:\n\n{raw_input}")
        ])
        
        # Parse output as JSON
        parser = JsonOutputParser()
        
        # Run the chain
        chain = prompt | llm | parser
        
        result = invoke_llm_with_retry(chain, {"raw_input": state['raw_input']})
        
        # Validate and store extracted data
        if isinstance(result, dict):
            state['extracted_json'] = result
            state['tenant_name'] = result.get('tenant_name')
            state['landlord_name'] = result.get('landlord_name')
            state['rent_amount'] = result.get('rent_amount')
            state['property_address'] = result.get('property_address')
            state['agreement_start_date'] = result.get('agreement_start_date')
            state['agreement_duration'] = result.get('agreement_duration')
            state['security_deposit'] = result.get('security_deposit')
            
            print(f"✅ [AISHA] Successfully extracted {len([v for v in result.values() if v])} fields")
            _record_activity(
                source="agent", staff_kind="agent", staff_short_name="aisha",
                capability_code="case.intake",
                summary=f"Extracted {len([v for v in result.values() if v])} fields from intake",
                payload={"sender": state.get("sender")},
                org_id=state.get('org_id'),
            )

        else:
            raise ValueError("Aisha did not return valid JSON")

    except Exception as e:
        error_msg = f"Aisha intake failed: {str(e)}"
        print(f"❌ [AISHA] {error_msg}")
        state['errors'].append(error_msg)
        state['extracted_json'] = None
        _record_activity(
            source="agent", staff_kind="agent", staff_short_name="aisha",
            capability_code="case.intake", summary=error_msg, status="error",
            org_id=state.get('org_id'),
        )


    state['timestamps']['aisha_end'] = datetime.now().isoformat()
    return state


@traceable(name="Guardrail_Regex_Validator")
def guardrail_node(state: AgentState) -> AgentState:
    """
    Node 1.5: Guardrail - Prevents LLM hallucination before drafting begins.
    Hard fails if critical data is missing or fails regex validation.
    """
    print("\n🛡️ [GUARDRAIL] Validating Aisha's extraction to prevent hallucinations")
    state['current_node'] = 'guardrail'
    if 'timestamps' not in state or state['timestamps'] is None:
        state['timestamps'] = {}
    state['timestamps']['guardrail_start'] = datetime.now().isoformat()
    state['guardrail_passed'] = False

    def _finish():
        state['timestamps']['guardrail_end'] = datetime.now().isoformat()
        return state

    if not state.get('extracted_json'):
        print("❌ [GUARDRAIL] Failed: No extracted data to validate.")
        state['errors'].append("Guardrail Failed: No extracted JSON.")
        return _finish()

    # Critical Field Check
    critical_fields = ['tenant_name', 'landlord_name', 'rent_amount', 'property_address']
    for field in critical_fields:
        if not state.get(field):
            error_msg = f"Guardrail Failed: Missing critical field '{field}'"
            print(f"❌ [GUARDRAIL] {error_msg}")
            state['errors'].append(error_msg)
            return _finish()

    # Regex Anti-Hallucination Check: Rent amount must contain numbers
    rent_val = str(state.get('rent_amount', ''))
    if not re.search(r'\d+', rent_val):
        error_msg = f"Guardrail Failed: 'rent_amount' ({rent_val}) does not contain valid numbers. Possible hallucination."
        print(f"❌ [GUARDRAIL] {error_msg}")
        state['errors'].append(error_msg)
        return _finish()

    state['guardrail_passed'] = True
    print("✅ [GUARDRAIL] All anti-hallucination checks passed.")
    return _finish()



def _extract_numeric(val: Any) -> Optional[float]:
    """Extract numeric value from a string like '₹25,000 per month' or '11 months'"""
    if val is None:
        return None
    try:
        # Remove commas and non-numeric characters except decimal point
        cleaned = re.sub(r'[^\d.]', '', str(val))
        return float(cleaned) if cleaned else None
    except ValueError:
        return None


# ============================================================================
# NODE 1.7: THE BOUNCER (Mathematical Validation)
# ============================================================================

@traceable(name="Bouncer_Math_Validator")
def bouncer_node(state: AgentState) -> AgentState:
    """
    Node 1.7: The Bouncer - Mathematically verifies stamp duty paid.
    """
    print("\n⚖️ [BOUNCER] Verifying stamp duty calculations")
    state['current_node'] = 'bouncer'
    state['timestamps']['bouncer_start'] = datetime.now().isoformat()
    state['bouncer_passed'] = False

    def _finish():
        state['timestamps']['bouncer_end'] = datetime.now().isoformat()
        return state

    # Extract required values
    rent = _extract_numeric(state.get('rent_amount'))
    duration_str = state.get('agreement_duration', '')
    # Extract months from "11 months" or "1 year"
    months = 0
    if duration_str:
        # Extract all numeric tokens and their associated units
        # Matches "1.5 years", "6 months", "1yr", etc.
        duration_tokens = re.findall(r'(\d+(?:\.\d+)?)\s*([a-zA-Z]*)', duration_str.lower())
        if duration_tokens:
            total_months = 0.0
            for val_str, unit in duration_tokens:
                val = float(val_str)
                if 'year' in unit or 'yr' in unit:
                    total_months += val * 12
                else:
                    # Assume months if unit is 'month', 'mo', or unspecified
                    total_months += val
            months = int(round(total_months))
        else:
            # Fallback: just extract any number
            tokens = re.findall(r'(\d+(?:\.\d+)?)', duration_str)
            if tokens:
                val = float(tokens[0])
                months = int(round(val * 12)) if any(u in duration_str.lower() for u in ['year', 'yr']) else int(round(val))

    paid = _extract_numeric(state.get('stamp_duty_paid'))

    if rent is None or months == 0 or paid is None:
        error_msg = f"Bouncer Failed: Missing mathematical inputs (Rent: {rent}, Duration: {months}, Paid: {paid})"
        print(f"❌ [BOUNCER] {error_msg}")
        state['errors'].append(error_msg)
        state['bouncer_feedback'] = error_msg
        return _finish()

    # Calculation: Expected = (Rent * Months) * 0.003
    expected = (rent * months) * 0.003

    # Tolerance: ±50 units (rounding)
    if abs(paid - expected) <= 50:
        state['bouncer_passed'] = True
        print(f"✅ [BOUNCER] Stamp duty verified: Found ₹{paid}, Expected ₹{expected:.2f}")
        _record_activity(
            source="agent", staff_kind="agent", staff_short_name="bouncer",
            capability_code="case.validate",
            summary=f"Stamp duty verified: ₹{paid} paid vs ₹{expected:.2f} expected",
            org_id=state.get('org_id'),
            payload={"expected": expected, "actual": paid},
        )
    else:
        error_msg = f"Bouncer Failed: Expected approx ₹{expected:.2f} (0.3% of {rent} * {months}), but found ₹{paid}"
        print(f"❌ [BOUNCER] {error_msg}")
        state['errors'].append(error_msg)
        state['bouncer_feedback'] = error_msg
        _record_activity(
            source="agent", staff_kind="agent", staff_short_name="bouncer",
            capability_code="case.validate",
            summary=error_msg,
            status="error",
            org_id=state.get('org_id'),
            payload={"expected": expected, "actual": paid},
        )

    return _finish()


DRAFTER_SYSTEM_PROMPT = """You are the Drafter, a Legal Architect AI for AG Associates.
Your role is to create professional rental agreements by combining templates with extracted data.

YOUR TASK:
1. Review the extracted tenant/landlord information
2. Use the provided template content as the base structure
3. Inject the extracted variables into appropriate sections
4. Maintain legal language and formatting
5. Ensure all placeholders are replaced with actual data
6. Add today's date as the agreement execution date
7. Format the output as clean Markdown suitable for PDF conversion

IMPORTANT:
- Preserve all legal clauses and terms from the template
- Only replace variable placeholders (marked as {{VARIABLE}} or similar)
- If any critical information is missing, note it at the end under "PENDING INFORMATION"
- Output the complete agreement document

TEMPLATE STRUCTURE TO FOLLOW:
- Title and Parties section
- Property Description
- Term and Rent details
- Security Deposit clause
- Rights and Obligations
- Signatures section
"""


def drafter_node(state: AgentState) -> AgentState:
    """
    Node 2: Drafter - Find template and generate document
    """
    print("\n📝 [DRAFTER] Starting document drafting")
    state['current_node'] = 'drafter'
    state['timestamps']['drafter_start'] = datetime.now().isoformat()
    state['revision_count'] = state.get('revision_count', 0) + 1
    
    try:
        # Check if we have extracted data
        if not state.get('extracted_json'):
            raise ValueError("No extracted data available from Aisha")
        
        # Build search query from extracted data
        search_query = f"Maharashtra rent agreement {state.get('property_address', '')}"
        
        # Perform similarity search to find best template
        templates = similarity_search(search_query, limit=3)
        
        if not templates:
            # Fallback: get any Maharashtra rent agreement template
            conn = get_db_connection()
            try:
                cur = conn.cursor()
                try:
                    cur.execute("""
                        SELECT id, title, content, language
                        FROM legal_templates
                        WHERE template_type = 'rent_agreement'
                        AND jurisdiction = 'Maharashtra'
                        LIMIT 1
                    """)
                    fallback_templates = cur.fetchall()
                finally:
                    cur.close()
            finally:
                conn.close()

            if fallback_templates:
                templates = [dict(t) for t in fallback_templates]
            else:
                raise ValueError("No suitable templates found in database")
        
        # Select best template
        best_template = templates[0]
        state['template_id'] = best_template['id']
        template_content = best_template['content']
        state['template_content'] = template_content
        
        print(f"📄 [DRAFTER] Selected template: {best_template['title']} (ID: {best_template['id']})")
        
        # Initialize LLM
        llm = ChatOpenAI(
            model=LLM_MODEL_NAME,
            openai_api_base=LLM_BASE_URL,
            openai_api_key=os.environ.get("LLM_API_KEY", "not-needed"),
            temperature=0.3
        )
        
        # Create prompt
        prompt = ChatPromptTemplate.from_messages([
            ("system", DRAFTER_SYSTEM_PROMPT),
            ("human", """
Extracted Data:
{extracted_data}

Template Content:
{template_content}

Generate the complete rental agreement document:
""")
        ])
        
        chain = prompt | llm
        
        # Prepare extracted data as string
        extracted_str = json.dumps(state['extracted_json'], indent=2, ensure_ascii=False)
        
        # Generate the document
        result = invoke_llm_with_retry(chain, {
            "extracted_data": extracted_str,
            "template_content": template_content
        })
        
        state['drafted_document'] = result.content
        
        # Convert to PDF using ReportLab
        from pdf_generator import convert_to_pdf
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        pdf_filename = f"agreement_{state['sender']}_{timestamp}"
        
        # Ensure output directory exists
        from config import OUTPUT_DIR
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        
        # Save markdown version
        md_path = f"{OUTPUT_DIR}/{pdf_filename}.md"
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(result.content)
        
        # Generate PDF
        try:
            pdf_path = convert_to_pdf(result.content, f"{state['sender']}_{timestamp}")
            state['pdf_path'] = pdf_path
            print("✅ [DRAFTER] Document drafted and saved:")
            print(f"   Markdown: {md_path}")
            print(f"   PDF: {pdf_path}")
        except Exception as pdf_error:
            print(f"⚠️ [DRAFTER] PDF generation failed: {str(pdf_error)}")
            print(f"   Markdown saved: {md_path}")
            state['pdf_path'] = md_path  # Fallback to markdown path

        _record_activity(
            source="agent", staff_kind="agent", staff_short_name="drafter",
            capability_code="case.draft",
            summary=f"Drafted document (revision {state.get('revision_count')})",
            payload={"template_id": state.get("template_id"), "pdf_path": state.get("pdf_path")},
            org_id=state.get('org_id'),
        )


        # Success — don't clear state['errors']; prior nodes may have added entries.
        
    except Exception as e:
        error_msg = f"Drafter failed: {str(e)}"
        print(f"❌ [DRAFTER] {error_msg}")
        state['errors'].append(error_msg)
        state['drafted_document'] = None
    
    state['timestamps']['drafter_end'] = datetime.now().isoformat()
    return state


# ============================================================================
# NODE 3: AUDITOR (Quality Assurance)
# ============================================================================

AUDITOR_SYSTEM_PROMPT = """You are the Auditor, a Quality Assurance AI for AG Associates Legal.
Your role is to verify that the drafted agreement accurately reflects the extracted requirements.

YOUR TASK:
1. Compare the extracted variables from Aisha with the drafted document
2. Verify all critical information is correctly included:
   - Tenant name appears correctly
   - Landlord name appears correctly
   - Rent amount is stated accurately
   - Property address is complete and correct
   - Agreement dates are properly specified
   - Security deposit is mentioned
3. Check for legal consistency and completeness
4. Identify any discrepancies or missing information

OUTPUT FORMAT:
Return a JSON object with:
{{
    "passed": true/false,
    "score": 0-100,
    "issues": ["list of issues found"],
    "feedback": "detailed feedback for improvements",
    "missing_fields": ["list of missing critical fields"]
}}

CRITICAL:
- If score >= 85 and no critical issues: passed = true
- If score < 85 or critical issues exist: passed = false
- Be thorough but reasonable - minor formatting issues shouldn't fail the audit
"""


def auditor_node(state: AgentState) -> AgentState:
    """
    Node 3: Auditor - Quality assurance check
    """
    print("\n🔍 [AUDITOR] Starting quality audit")
    state['current_node'] = 'auditor'
    state['timestamps']['auditor_start'] = datetime.now().isoformat()
    
    try:
        # Check if we have a drafted document
        if not state.get('drafted_document'):
            raise ValueError("No drafted document available for audit")
        
        # Initialize LLM
        llm = ChatOpenAI(
            model=LLM_MODEL_NAME,
            openai_api_base=LLM_BASE_URL,
            openai_api_key=os.environ.get("LLM_API_KEY", "not-needed"),
            temperature=0.1
        )
        
        # Create prompt
        prompt = ChatPromptTemplate.from_messages([
            ("system", AUDITOR_SYSTEM_PROMPT),
            ("human", """
Extracted Requirements (from Aisha):
{extracted_json}

Drafted Document:
{drafted_document}

Perform the quality audit and return JSON:
""")
        ])
        
        # Parse output as JSON
        parser = JsonOutputParser()
        
        chain = prompt | llm | parser
        
        # Prepare inputs
        extracted_str = json.dumps(state['extracted_json'], indent=2, ensure_ascii=False)
        
        # Run audit
        result = invoke_llm_with_retry(chain, {
            "extracted_json": extracted_str,
            "drafted_document": state['drafted_document']
        })
        
        # Store audit results
        state['audit_passed'] = result.get('passed', False)
        state['audit_feedback'] = result.get('feedback', '')
        
        issues = result.get('issues', [])
        score = result.get('score', 0)
        
        print(f"📊 [AUDITOR] Audit Score: {score}/100")
        print(f"✅ [AUDITOR] Audit Passed: {state['audit_passed']}")
        _record_activity(
            source="agent", staff_kind="agent", staff_short_name="auditor",
            capability_code="case.audit",
            summary=f"Audit score {score}/100 — {'passed' if state['audit_passed'] else 'failed'}",
            payload={"score": score, "issues_count": len(issues)},
            status="ok" if state['audit_passed'] else "warn",
            org_id=state.get('org_id'),
        )

        
        if issues:
            print(f"⚠️ [AUDITOR] Issues found: {len(issues)}")
            for issue in issues[:3]:  # Show first 3 issues
                print(f"   - {issue}")
        
        # Success — don't clear state['errors']; prior nodes may have added entries.
        
    except Exception as e:
        error_msg = f"Auditor failed: {str(e)}"
        print(f"❌ [AUDITOR] {error_msg}")
        state['errors'].append(error_msg)
        state['audit_passed'] = False
        state['audit_feedback'] = f"Audit could not be completed: {str(e)}"
    
    state['timestamps']['auditor_end'] = datetime.now().isoformat()
    return state


# ============================================================================
# GRAPH BUILDING & ROUTING
# ============================================================================

def should_revise(state: AgentState) -> str:
    """
    Conditional edge: Decide whether to revise or finish
    """
    if state['audit_passed']:
        print("✅ Audit passed - proceeding to finish")
        return "finish"
    elif state['revision_count'] > 3:
        print("⚠️ Max revisions reached - finishing anyway")
        return "finish"
    else:
        print(f"🔄 Audit failed - revising (attempt {state['revision_count'] + 1})")
        return "revise"


def build_agent_graph() -> StateGraph:
    """
    Build the LangGraph workflow: Aisha -> Guardrail -> Bouncer -> Drafter -> Auditor -> (Finish or Revise)
    """
    # Initialize the graph
    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("aisha_intake", aisha_intake_node)
    workflow.add_node("guardrail", guardrail_node)
    workflow.add_node("bouncer", bouncer_node)
    workflow.add_node("drafter", drafter_node)
    workflow.add_node("auditor", auditor_node)

    # Set entry point
    workflow.set_entry_point("aisha_intake")

    # Add edges
    workflow.add_edge("aisha_intake", "guardrail")

    def check_guardrail(state: AgentState) -> str:
        if not state.get('guardrail_passed', False):
            print("🛑 Guardrail blocked execution. Ending workflow early.")
            return "finish"
        return "continue"

    workflow.add_conditional_edges(
        "guardrail",
        check_guardrail,
        {
            "finish": END,
            "continue": "bouncer"
        }
    )

    def check_bouncer(state: AgentState) -> str:
        if not state.get('bouncer_passed', False):
            print("🛑 Bouncer blocked execution: Stamp duty mismatch. Ending workflow early.")
            return "finish"
        return "continue"

    workflow.add_conditional_edges(
        "bouncer",
        check_bouncer,
        {
            "finish": END,
            "continue": "drafter"
        }
    )

    workflow.add_edge("drafter", "auditor")

    # Add conditional edge from auditor
    workflow.add_conditional_edges(
        "auditor",
        should_revise,
        {
            "finish": END,
            "revise": "drafter"
        }
    )

    # Compile the graph
    app = workflow.compile()

    return app



# ============================================================================
# MAIN EXECUTION FUNCTION
# ============================================================================

def process_rental_request(raw_input: str, sender: str = "whatsapp_user", org_id: Optional[str] = None) -> Dict[str, Any]:
    """
    Main function to process a rental agreement request through the agent pipeline

    Args:
        raw_input: The user's raw message with rental details
        sender: Identifier for the message sender
        org_id: Organization ID for multi-tenant isolation

    Returns:
        Dictionary containing the final state and results
    """
    print("\n" + "="*60)
    print("🚀 STARTING AG ASSOCIATES AI WORKFLOW")
    print("="*60)

    # Initialize state
    initial_state = AgentState(
        raw_input=raw_input,
        sender=sender,
        org_id=org_id,
        tenant_name=None,
        landlord_name=None,
        rent_amount=None,
        property_address=None,
        agreement_start_date=None,
        agreement_duration=None,
        security_deposit=None,
        stamp_duty_paid=None,
        extracted_json=None,
        template_id=None,
        template_content=None,
        drafted_document=None,
        pdf_path=None,
        guardrail_passed=False,
        bouncer_passed=False,
        bouncer_feedback=None,
        audit_passed=False,
        audit_feedback=None,
        revision_count=0,
        current_node="init",
        errors=[],
        timestamps={}
    )

    
    # Build and run the graph
    graph = build_agent_graph()
    
    try:
        final_state = graph.invoke(initial_state)
        
        print("\n" + "="*60)
        print("✅ WORKFLOW COMPLETED")
        print("="*60)
        
        # Summary
        print("\n📋 SUMMARY:")
        print(f"   Tenant: {final_state.get('tenant_name') or 'N/A'}")
        print(f"   Property: {(final_state.get('property_address') or 'N/A')[:50]}...")
        print(f"   Rent: {final_state.get('rent_amount') or 'N/A'}")
        print(f"   Document: {final_state.get('pdf_path', 'Not generated')}")
        print(f"   Audit: {'PASSED' if final_state.get('audit_passed') else 'FAILED'}")
        print(f"   Revisions: {final_state.get('revision_count', 0)}")
        
        return {
            "success": True,
            "state": final_state,
            "document_path": final_state.get('pdf_path'),
            "audit_passed": final_state.get('audit_passed'),
            "extracted_data": final_state.get('extracted_json')
        }
        
    except Exception as e:
        print(f"\n❌ WORKFLOW FAILED: {str(e)}")
        return {
            "success": False,
            "error": str(e),
            "state": initial_state
        }


# Example usage and testing
if __name__ == "__main__":
    # Test input
    test_message = """
    Hi, I need a rental agreement for my new place in Pune.
    Tenant name is Rahul Patil, and I'm the landlord - Suresh Deshmukh.
    The property is at Flat 201, Krishna Heights, Karve Road, Pune 411004.
    Monthly rent will be ₹28,000, and we're doing an 11-month agreement starting March 1st, 2024.
    Security deposit is ₹84,000 (3 months rent).
    Please prepare the agreement.
    """
    
    result = process_rental_request(test_message, "test_user_001")
    
    if result["success"]:
        print("\n✨ Agreement generation successful!")
    else:
        print(f"\n❌ Error: {result.get('error')}")
