"""Agent Bus — Redis Streams based agent-to-agent communication.

Message schema (stored as JSON in Redis Stream):
    id:          UUID (auto-generated by Redis)
    source:      agent name (e.g. "auditor", "vyasa")
    target:      agent name, "*" for broadcast, or "aisha" for user-facing
    type:        "request" | "response" | "broadcast" | "directive"
    payload:     dict (arbitrary data)
    conversation_id: optional UUID for multi-turn conversations
    correlation_id: UUID to pair request/response
    hop_count:   int (max 5 to prevent infinite loops)
    timestamp:   ISO datetime

Consumer groups ensure each agent gets exactly-once delivery.
MAX_HOPS = 5 prevents infinite broadcast loops.
"""

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Any, Callable, Optional

import redis.asyncio as aioredis

logger = logging.getLogger(__name__)

REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "HipS3BPnNWaiGHJDNEIf0upP9NAiDguW")
AGENT_BUS_STREAM = "agent:bus"
AGENT_BUS_GROUP = "agent:bus:consumers"
MAX_HOPS = 5


def _redis_url() -> str:
    url = REDIS_URL
    if REDIS_PASSWORD and "redis://" in url and "@" not in url:
        url = url.replace("redis://", f"redis://:{REDIS_PASSWORD}@")
    return url


async def get_bus_redis() -> aioredis.Redis:
    return aioredis.from_url(
        _redis_url(),
        decode_responses=True,
        socket_connect_timeout=10,
        socket_timeout=None,
    )


async def ensure_bus_group():
    r = await get_bus_redis()
    try:
        await r.xgroup_create(AGENT_BUS_STREAM, AGENT_BUS_GROUP, id="0", mkstream=True)
    except aioredis.ResponseError as e:
        if "BUSYGROUP" not in str(e):
            raise


async def send_message(
    source: str,
    target: str,
    payload: dict,
    *,
    msg_type: str = "request",
    conversation_id: Optional[str] = None,
    correlation_id: Optional[str] = None,
) -> str:
    msg_id = str(uuid.uuid4())
    msg = {
        "id": msg_id,
        "source": source,
        "target": target,
        "type": msg_type,
        "payload": json.dumps(payload, default=str),
        "conversation_id": conversation_id or "",
        "correlation_id": correlation_id or msg_id,
        "hop_count": "0",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    r = await get_bus_redis()
    await r.xadd(AGENT_BUS_STREAM, msg, maxlen=10000)
    logger.info("[BUS] %s → %s (%s)", source, target, msg_type)
    return msg_id


async def listen_agent(
    agent_name: str,
    handler: Callable[[dict], Any],
    *,
    consumer_id: str = "worker1",
    block_ms: int = 5000,
):
    r = await get_bus_redis()
    consumer_name = f"{agent_name}:{consumer_id}"
    await ensure_bus_group()

    while True:
        try:
            results = await r.xreadgroup(
                groupname=AGENT_BUS_GROUP,
                consumername=consumer_name,
                streams={AGENT_BUS_STREAM: ">"},
                count=10,
                block=block_ms,
            )
        except aioredis.ResponseError:
            await ensure_bus_group()
            continue

        if not results:
            continue

        for stream_name, messages in results:
            for msg_id, fields in messages:
                try:
                    msg = {k: v for k, v in fields.items() if k and v}
                    if int(msg.get("hop_count", 0)) >= MAX_HOPS:
                        logger.warning(
                            "[BUS] Max hops exceeded for %s, dropping", msg_id
                        )
                        await r.xack(AGENT_BUS_STREAM, AGENT_BUS_GROUP, msg_id)
                        continue

                    if msg.get("target") not in (agent_name, "*"):
                        continue

                    msg["payload"] = json.loads(msg.get("payload", "{}"))
                    msg["hop_count"] = int(msg.get("hop_count", 0))

                    await handler(msg)
                    await r.xack(AGENT_BUS_STREAM, AGENT_BUS_GROUP, msg_id)
                except Exception as e:
                    logger.error("[BUS] Error handling msg %s: %s", msg_id, e)


async def request_response(
    source: str,
    target: str,
    payload: dict,
    *,
    timeout: float = 30.0,
    conversation_id: Optional[str] = None,
) -> Optional[dict]:
    correlation_id = str(uuid.uuid4())
    r = await get_bus_redis()
    response_key = f"agent:response:{correlation_id}"

    await send_message(
        source=source,
        target=target,
        payload=payload,
        msg_type="request",
        conversation_id=conversation_id,
        correlation_id=correlation_id,
    )

    raw = await r.brpoplpush(response_key, response_key, timeout=int(timeout))
    if raw:
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return None
    return None


async def publish_response(
    source: str,
    target: str,
    payload: dict,
    correlation_id: str,
    conversation_id: Optional[str] = None,
):
    response_key = f"agent:response:{correlation_id}"
    r = await get_bus_redis()
    data = json.dumps(
        {"source": source, "target": target, "payload": payload}, default=str
    )
    await r.lpush(response_key, data)
    await r.expire(response_key, 60)
