"""Shared LangGraph state schema for the AG Associates AI pipeline."""

from typing import Any, Dict, List, Optional, TypedDict


class AgentState(TypedDict):
    """
    State schema for the agent workflow. Tracks all variables through the
    pipeline: Aisha (intake) → Guardrail → Bouncer → Drafter → Auditor.
    """

    # Input from user
    raw_input: str
    sender: str
    org_id: Optional[str]

    # Extracted by Aisha
    tenant_name: Optional[str]
    landlord_name: Optional[str]
    rent_amount: Optional[str]
    property_address: Optional[str]
    agreement_start_date: Optional[str]
    agreement_duration: Optional[str]
    security_deposit: Optional[str]
    stamp_duty_paid: Optional[str]
    extracted_json: Optional[Dict[str, Any]]

    # Generated by Drafter
    template_id: Optional[int]
    template_content: Optional[str]
    drafted_document: Optional[str]
    pdf_path: Optional[str]

    # Guardrail / Bouncer result
    guardrail_passed: bool
    bouncer_passed: bool
    bouncer_feedback: Optional[str]

    # Audit results
    audit_passed: bool
    audit_feedback: Optional[str]
    revision_count: int

    # Metadata
    current_node: str
    errors: List[str]
    timestamps: Dict[str, str]
